### ISSUE TITLE
How to call 'composite' marks

### ISSUE THREAD

**Issue by atepoorthuis** [spatialnetworkslab/vue-gg#19]
In the other repo, we kinda use 'Layer' for this. Perhaps Composite Mark is also quite a descriptive name. Sometimes, in the literature, 'glyph' is used, but generally glyph is specially used for complex shapes that are plotted at a specific point (so they replace a more simple point/circle in this sense). When talking about composite marks, I am thinking of the box+whiskers in a boxplot. Perhaps also something as a treemap (https://spatialnetworkslab.github.io/docs-vue-graphics-grammar/graphs/treemap.html). Some cases are clearly high-level charts such as lollipops (https://spatialnetworkslab.github.io/docs-vue-graphics-grammar/graphs/lollipop.html) but I think that the box+whiskers is a bit in between a low-level Mark and a high-level Chart. Perhaps it is the only exception though?

**Comment by luucvanderzee** [comment]
Now that we can use `Section`s as entry points for data and to 'de-group' data, I think we can solve a lot of these by examples with `Section`s, no?

**Comment by atepoorthuis** [comment]
Yes - agreed on the implementation. I meant more what semantic label do we use to refer to these components?

**Comment by atepoorthuis** [comment]
I think maybe we keep it simple for now and put these all in glyphs rather than introduce a new category?
![image](https://user-images.githubusercontent.com/1752727/51232262-22747f80-19a1-11e9-9813-ae0177773b77.png)
