### ISSUE TITLE
Create Trail Mark

### ISSUE THREAD

**Issue by atepoorthuis** [spatialnetworkslab/vue-gg#23]
The current implementation of Line/MultiLine doesn't allow for variable line width (like we have here: https://spatialnetworkslab.github.io/docs-vue-graphics-grammar/layers/multilinelayer.html#color-and-stroke-width). I think it probably makes most sense to implement a Trail mark (https://vega.github.io/vega/docs/marks/trail/) for this functionality. The Line/MultiLine marks are both a single `path`, generated by d3.line (and thus allow for curve interpolation etc.). The Trail mark would be a Line per segment.

**Comment by bianchi-dy** [comment]
See [multiline-trail branch in github/vue-gg](https://github.com/spatialnetworkslab/vue-gg/tree/multiline-trail) - controlling opacity is a bit wonky because I use ~150 segments to draw the increasing width but otherwise it works.

**Comment by atepoorthuis** [comment]
Nice! I am a little in doubt now what the best/most useful implementation of this Mark would be. I tried to draw:

![image](https://user-images.githubusercontent.com/1752727/51292925-8a7da100-1a47-11e9-98f1-1b891b647a4e.png)

Your current implementation in the third one. With a similar philosophy we could also go for the second option. Basically an area Mark for which you need to calculate the corner points based on the width of the 'line'. This would save on the segment interpolation you are doing now. Even simpler would just be to draw a line per segment of the trajectory. This has one downside: you can only attach data (such as line width) to the segment as a whole. Depends on your data: is your unit of analysis based on the edges or nodes between the edges.
