### ISSUE TITLE
Intuitive positioning for chart elements

### ISSUE THREAD

**Issue by atepoorthuis** [spatialnetworkslab/vue-gg#35]
This is in relation to #33. Right now, we always require the user to set the position of an element in absolute coordinates. This gets cumbersome pretty fast. I think we should add option to do relative positioning (top, bottom, left, right). By default we can use something sensible, similar to how @GraceGSy set this up in the old repo. Where `<plot-title text="An Appeeling Graph" />` would be centered by default:
![image](https://user-images.githubusercontent.com/1752727/51026875-7dd1f680-15ca-11e9-970f-07ca31e80839.png)

This becomes especially handy when, for example, you'd want to add a title to every facet.

**Comment by luucvanderzee** [comment]
@GraceGSy 

> [On a side note, would it be nice to work title labels into sections as well, in case we want to label different sections once we get to faceting?]

Should we close this issue and make that another issue, with some more explanation?

**Comment by GraceGSy** [comment]
@luucvanderzee Hm! It seems I wrote this a long time ago. Currently we can add title labels to sections using the `<vgg-plot-title>` component, which should be sufficient to address this comment of mine. What do you think?

**Comment by atepoorthuis** [comment]
Fixed in fc62272
