### ISSUE TITLE
Composition/layout logic

### ISSUE THREAD

**Issue by atepoorthuis** [spatialnetworkslab/vue-gg#39]
Currently, our main way of composing different plots/layers is the `Section`. Sections can be absolutely positioned within the graphic but this needs to happen by manually setting the x/y/dimensions. Especially for faceting (but also for simpler things, like placing two plots side-by-side), it would be useful to have a layout or composition logic. For reference, [Vega's composition approach](https://vega.github.io/vega-lite/docs/composition.html), [ggplot's facets](https://ggplot2.tidyverse.org/reference/facet_grid.html) and [patchwork](https://github.com/thomasp85/patchwork), a composition utility for ggplot plots.

Preferred approaches for implementing this within `vue-gg`?

**Comment by luucvanderzee** [comment]
Largely fixed in #54
