### ISSUE TITLE
Categorical color scale

### ISSUE THREAD

**Issue by luucvanderzee** [spatialnetworkslab/vue-gg#61]
Categorical color scales are currently not supported. 

It would be nice if we can:

- [x] Have one or more default categorical color schemes
- [x] Have the option to define your own color schemes. But I just realized that I replaced the `range` scaling option with `rangeMin` and `rangeMax`. I suppose we should re-introduce the `range` option, but make sure it is not used in combination with `rangeMin` and `rangeMax`? Or replace `rangeMin` and `rangeMax` altogether? What do you think? Maybe it's good to have both, since the `domain` also has `domain`, `domainMin`, `domainMax` etc.
- [x] Throw a warning if you have too many/few categories in your data for the chosen color scheme (default or self-specified) and have a fallback color/cycle through the available options/something else

**Comment by bianchi-dy** [comment]
> Have the option to define your own color schemes. But I just realized that I replaced the range scaling option with rangeMin and rangeMax.

So from what I understand, it could be something like

`{ domain: "someVar", rangeMin: "green", rangeMax: "orange" }` where we'd need to interpolate a color scale from green to orange?

**Comment by bianchi-dy** [comment]
>Have the option to define your own color schemes. But I just realized that I replaced the range scaling option with rangeMin and rangeMax.

So from what I understand, it could be something like

{ domain: "someVar", rangeMin: "green", rangeMax: "orange" } where we'd need to interpolate a color scale from green to orange?

**Comment by luucvanderzee** [comment]
@bianchi-dy i don't know... i am not sure if that makes sense for categorical data. maybe it would make sense for ordinal data? but i think it would be better to not use/allow `rangeMin` and `rangeMax` here, and just use `ranges` instead, like so

`{ domain: 'someVar', ranges: ['red', 'green', blue', 'orange'] } // assuming 'someVar' has 4 unique categories`

**Comment by bianchi-dy** [comment]
Since this is with reference to categorical data (i.e. things get enumerated by the order in which they appear), I've used `ranges` to define custom color scales in the `categoricalColor` branch.

**Comment by bianchi-dy** [comment]
I've gotten categorical color scales to work already (see [categoricalColor-fix](https://github.com/spatialnetworkslab/vue-gg/tree/categoricalColor-fix)), just waiting for categoricalShape (#72) to get merged to master first before I do a PR since the example in TestSymbol relies on Grace's code
