### ISSUE TITLE
Use of Plot Title _inside_ section throws error with hjust/vjust

### ISSUE THREAD

**Issue by atepoorthuis** [spatialnetworkslab/vue-gg#88]
It would be great to be able to give individual sections titles, especially for facets etc. I think the default way is to add the `plot-title` _outside_ of the Section. But this doesn't work with the `grid` and `repeat` components as they expect their direct children to only be sections. @GraceGSy?

```
<vgg-section
            :data="facet.grouped"
            :transform="[
              { groupBy: 'flat_type'},
              { summarise: { total_sales: { resale_price: 'count' } } }
            ]"
          >
            <vgg-plot-title
              :text="facet.town"
              :vjust="0"
            />
</vgg-section>
```
![image](https://user-images.githubusercontent.com/1752727/54931201-85f7cc00-4f53-11e9-96ec-9e7c099eafe5.png)

**Comment by GraceGSy** [comment]
Fixed! in #91
