### ISSUE TITLE
Allow domain min/max to be overwritten separately

### ISSUE THREAD

**Issue by atepoorthuis** [spatialnetworkslab/vue-gg#9]
Right now you either run with the computed domain or supply an Array `[min, max]` by hand. It would be very useful to overwrite only the min or max as that's a very common use case (e.g. make sure scale starts at some logical theoretical value etc.). See Vega's scale properties here as well: https://vega.github.io/vega/docs/scales/. (That domain midpoint is going to come in handy later too!).

**Comment by luucvanderzee** [comment]
Was solved [here](https://github.com/spatialnetworkslab/vue-gg/commit/fab47e15fe481f890108925e35f430d2e86f0ca5)
