### ISSUE TITLE
Interval scale: implement 'nice' ticks and fix tick-values prop

### ISSUE THREAD

**Issue by luucvanderzee** [spatialnetworkslab/vue-gg#98]
1. It is now only possible to use the bin boundaries as ticks, but this can get messy with a lot of bins:

![Screenshot from 2019-03-27 11-16-49](https://user-images.githubusercontent.com/13822005/55068314-d8370b00-5081-11e9-9570-37deb7763997.png)

Maybe find a good way to only show a few of these boundaries when 'nice' is set to `true`.

2. `:tick-values` prop is broken in general- the labels are not showing:

![Screenshot from 2019-03-27 11-18-37](https://user-images.githubusercontent.com/13822005/55068419-17655c00-5082-11e9-9aab-e379692612ed.png)

3. the `:tick-values` are broken for interval scales in particular, using pixel values instead of the appropriate domain:

```
<vgg-x-axis :scale="'bins'" :tick-values="[0, 200000, 400000, 600000, 800000]"/>
```

![Screenshot from 2019-03-27 11-20-40](https://user-images.githubusercontent.com/13822005/55068546-67442300-5082-11e9-9ebd-74e37776aae3.png)

**Comment by GraceGSy** [comment]
Fixed in #101
